### ISSUE TITLE
Add Up, Right, and Forward Vectors

### ISSUE THREAD

**Issue by wozniakty** [Circular-Studios/Dash#125]
We should have an Up Right and Forward vector based on a given transformation, for uses with things like cameras, etc.

This could probably go in Transform and be based on the rotation, or maybe should go into our fork of gl3n?

**Comment by dislogical** [comment]
I think this is definitely a Transform thing. I don't even know where it would go in gl3n.

**Comment by wozniakty** [comment]
Slipping this to 0.7.0

**Comment by dislogical** [comment]
Closed by #145.
