### ISSUE TITLE
Add string parameter to Input.addKeyDownEvent

### ISSUE THREAD

**Issue by PxlBuzzard** [Circular-Studios/Dash#141]
I would like to be able to do .addKeyDownEvent using a string as defined in Input.yml rather than hardcoding a value.

Current: 

``` d
Input.addKeyDownEvent( Keyboard.Escape, ( uint kc ) { currentState = EngineState.Quit; } );
```

New:

``` d
Input.addKeyDownEvent( "Back", ( uint kc ) { currentState = EngineState.Quit; } );
```

**Comment by dislogical** [comment]
Is [`getState`](https://github.com/Circular-Studios/Dash/blob/develop/source/utility/input.d#L239) not good enough?

**Comment by PxlBuzzard** [comment]
I've modified the issue to reflect my use case for wanting Input.get();
