### ISSUE TITLE
Add Hide function to GameObjects

### ISSUE THREAD

**Issue by wozniakty** [Circular-Studios/Dash#143]
A game developer may want to quickly/easily stop drawing an object without losing state information (for example, objects that you would like to see through but that maybe aren't actually clipped by the hardware yet).

Note: I'm not yet confident this makes sense as a GameObject function, since not all GameObjects are drawn anyways.  Maybe make a GameObject.disable(), and then it will not draw if it has a mesh, not light things if it contains a light, etc?  Feel free to suggest.

Current Use Case:  There are pipes on the walls in a current project.  Because of that, when viewing from outside, we'd like to clip the walls.  The flat surface of the wall is clipped by backface culling, but since the pipes are round, you see them through the walls.  It'd be preferred if we could just disable drawing on walls based on the camera direction.

**Comment by dislogical** [comment]
I would be careful with the `disable` function idea, as Unity uses this, but it also disables all events triggering on scripts. Is that what we want, or just no drawing?

**Comment by ericchristenson** [comment]
We could do something similar to the updateFlags in dgame, and fine tune it a bit.  Maybe have flags for update, draw, update/draw children, components...

**Comment by dislogical** [comment]
I really like that idea. This would also allow us to reuse our `pauseAll` and `resumeAll` functions.
