### ISSUE TITLE
Rework Mesh loading system

### ISSUE THREAD

**Issue by dislogical** [Circular-Studios/Dash#15]
[Assimp](http://assimp.sourceforge.net/index.html) is an object file importer that could replace the current model loading system.

[Also, it's already been ported to D](https://github.com/DerelictOrg/DerelictASSIMP3).

**Comment by PxlBuzzard** [comment]
Woops, now I know what that button does. :/

**Comment by wozniakty** [comment]
I think integrating Assimp would be a good idea, especially since it should support proven tangent and binormal calculations.  I am changing the name of this however, to show that I'd like us to finalize the mesh loading for milestone 2, regardless of how we do it.

**Comment by ericchristenson** [comment]
Artists would also like the ability to have quads and triangles in their models.

**Comment by dislogical** [comment]
As far as I can tell, AssImp will triangulate for you, so the let artists could give it either.
