### ISSUE TITLE
Use Default/Error Texture when Texture Not Found

### ISSUE THREAD

**Issue by wozniakty** [Circular-Studios/Dash#151]
When I name a texture in a material yaml that doesn't exist in the texture folder, it should warn/notify me that the texture name I was looking for was not found, and probably use a default/error texture for that texture.

Presumably, the default/error texture should be different for diffuse, normal, and specular

**Comment by wozniakty** [comment]
We should also do the same thing for Materials, I'm realizing.

**Comment by dislogical** [comment]
Uses a black default texture now.
