### ISSUE TITLE
Handle Textures with the Same Name

### ISSUE THREAD

**Issue by wozniakty** [Circular-Studios/Dash#161]
Texture images can have the same name with any file extension.  We should probably figure out if we want to do something when there are overlaps, and if not, document the order of preference it takes on file types so we can document it.

Example:
In folder I can have flat_n.png and flat_n.tga and I only access them through "flat_n"

**Comment by wozniakty** [comment]
At the moment, it seems that tga are prioritized by our system over png, based on some simple testing

**Comment by dislogical** [comment]
I'm pretty sure they just get loaded alphabetically, so that makes sense.
