### ISSUE TITLE
[Animation] More generic support

### ISSUE THREAD

**Issue by tmr9209** [Circular-Studios/Dash#175]
- [ ] Animation should be generalized to not crash for different animation setups and have error messages for these non-working setups.
- [x] Fix minor bug on some werewolf animation frames.
- [x] Make sure robot file is supported in Spectral Robot Task Force

**Comment by PxlBuzzard** [comment]
This will be closed with the knowledge that we have at least one working pipeline in place, but that bugs will be fixed as more animations and file formats are introduced.
