### ISSUE TITLE
Problem while compiling

### ISSUE THREAD

**Issue by acemi** [Circular-Studios/Dash#182]
On OSX 64 bit - dmd v2.065
I get the following error:

```
source/utility/input.d(326): Error: function utility.input.Input.mousePos has no return statement, but is expected to return a value of type Vector!(float, 2)
FAIL .dub/build/library-debug-posix.osx-x86_64-dmd-3C6E8969AD590B672545D425B0181F08 dash staticLibrary
Error executing command run: DMD compile run failed with exit code 1
```

**Comment by dislogical** [comment]
Unfortunately, we do not currently support OSX, only Windows and Linux. We've talked about implementing OSX support at some point (see #3), but until [DIP43](http://wiki.dlang.org/DIP43) is implemented, and we can use Cocoa, we do not plan on adding support.

That said, if you'd like to add support yourself, we're happy to review any pull requests submitted.

**Comment by acemi** [comment]
Thank you!
