### ISSUE TITLE
[Input] XInput support

### ISSUE THREAD

**Issue by PxlBuzzard** [Circular-Studios/Dash#185]
XInput is the currently accepted API in Windows to handle input devices such as gamepads and joysticks. Our [recent upgrade](https://github.com/Circular-Studios/Dash/pull/181) to Input was the first step towards supporting more types of input methods, and XInput is the next logical step forward.

**Comment by dislogical** [comment]
Closing, we'll use [SDL](http://libsdl.org/)'s input library, which has support for game pads. See #207.
