### ISSUE TITLE
Some static analysis issues

### ISSUE THREAD

**Issue by Hackerpilot** [Circular-Studios/Dash#197]
- [x] ./utility/tasks.d(44:10)[warn]: Variable startTime is never used
- [x] ./utility/tasks.d(269:10)[warn]: Variable startTime is never used
- [x] ./utility/tasks.d(295:10)[warn]: Variable startTime is never used
- [x] ./utility/tasks.d(322:10)[warn]: Variable startTime is never used
- [x] ./core/gameobject.d(125:14)[warn]: Variable foundClassName is never used
- [x] ./core/gameobject.d(126:22)[warn]: Variable className is never used
- [x] ./components/mesh.d(162:31)[warn]: Variable w is never used
- [x] ./components/mesh.d(207:31)[warn]: Variable w is never used
- [x] ./components/mesh.d(118:36)[warn]: Variable tempBone is never used
- [x] ./components/lights.d(173:14)[warn]: Variable bias is never used
- [x] ./utility/config.d(350:9)[warn]: Implicit concatenation of string literals

I don't think that the q{} syntax is correct for GLSL code. `#version 400` is not a valid token in D so a standard-compliant lexer will reject this code. `#line` is the only valid use of the # character according to the language spec.

**Comment by dislogical** [comment]
Thanks for the info! I'll go take a look though those warnings. I'm assuming you ran DScanner on the project?

As far as the token strings go, I've just looked at the docs again, and you're totally right. One solution I can think of is to list the `#version 400\n` as an enum string, and then just append it to the beginning of each shader, as it should never be different for different shaders. Does that seem like a reasonable alternative?

**Comment by Hackerpilot** [comment]
Yes. I'm trying DScanner against several projects to find bugs in my analysis checks (and the projects themselves). Your project helped me discover that I wasn't handling byte order marks properly. You'll want to use https://github.com/Hackerpilot/Dscanner/commit/db84119e33f6ba99f29eff555082901ec0560b16 or newer if you run the checks yourself.

Regarding the GLSL code: It would work, but the point of the q{} string literal is that everything inside of it is supposed to be valid D tokens. If it's actualy GLSL code you may want to use one of the other types of string literal.

**Comment by dislogical** [comment]
Theoretically, _most_ valid GLSL code is valid C code, which in turn should be valid D code, so I think we'll keep it for now. If it becomes a problem in the future, we'll know where to start looking.

Thanks for the suggestions, though!
