### ISSUE TITLE
`core` modules could end up clashing with druntime

### ISSUE THREAD

**Issue by ghost** [Circular-Studios/Dash#199]
You're free to use `core` and `std` since these are not reserved identifiers per say, but if e.g. Druntime ever implements a `package.d` module or any other module with the same name as one of Dash'es core modules it's going to cause conflicts. It's probably better to be safe than sorry and consider renaming `core` to something else before it's too late.

**Comment by dislogical** [comment]
Checkout #198, which should solve the problem.

**Comment by ghost** [comment]
Ah, sorry for the dupe!
