### ISSUE TITLE
Implement Render Pipeline

### ISSUE THREAD

**Issue by dislogical** [Circular-Studios/Dash#2]
We need to design and implement a shader pipeline for efficiently drawing objects.
Things To Do:
- [x] Set up textures for deferred rendering
- [ ] Shut down textures for deferred rendering
- [ ] Determine object render framework
- [x] Implement Shader compiling
- [x] Implement object loading

**Comment by wozniakty** [comment]
Pipeline works.  Code for normal maps and mesh loading appears to have issues.
