### ISSUE TITLE
dash-game broken dependency

### ISSUE THREAD

**Issue by darthbanana13** [Circular-Studios/Dash#200]
Grabbed dash-game 0.6.3 for windows, running it gives it this error:
[DEBUG]   Initializing...
dyaml.exception.YAMLException@....\Users\colde_000\AppData\Roaming\dub\packages\dyaml-master\source\dyaml\loader.d(124): Unable to open file ../Config/Config.yml for YAML loading: Cannot open or create file '../Config/Config.yml'

I could not find a place to configure the path to the file but out-of-the-box dash-game-windows doesn't work.
![dash](https://cloud.githubusercontent.com/assets/1921396/3027566/17272238-e024-11e3-829f-980ec6e83206.jpg)

**Comment by dislogical** [comment]
`v0.6.3` is actually super old, so it doesn't really surprise me that it's broken. I think the bigger issue is that we need to put up more zip files like that one for people to test with. I just put one up for [`v0.9.0`](https://github.com/Circular-Studios/Dash/releases/tag/v0.9.0), let me know if you have any problems with that one.

**Comment by darthbanana13** [comment]
Downloaded it, and because there's no "Dash Game" I've overwritten the v0.6.3 archive with what you put v0.9.0.
![dash](https://cloud.githubusercontent.com/assets/1921396/3028113/518a1e76-e029-11e3-8389-9622c64f5d83.jpg)
And a dash.log with:
![dash log](https://cloud.githubusercontent.com/assets/1921396/3028123/5f4713de-e029-11e3-899f-849744ded07f.jpg)
The textures that are reported missing are in the Textures folder so my guess is that it's probably looking elsewhere for them.

**Comment by wozniakty** [comment]
So I think the problem is some of the assets/files got mixed up between an old version of the Sample game and what you've downloaded.

What you'll want to do is get the newest [Dash Sample Game](https://github.com/Circular-Studios/Sample-Dash-Game) and run that.

**Comment by dislogical** [comment]
That said, we do need to make sure the .zips we provide are functional.

**Comment by dislogical** [comment]
Just finally got around to fixing this. The new [`dash-game-v0.9.0.zip`](https://github.com/Circular-Studios/Dash/releases/tag/v0.9.0) should be functional.
