### ISSUE TITLE
Singling out the windowing adapter

### ISSUE THREAD

**Issue by p0nce** [Circular-Studios/Dash#228]
I see that you've done work to have keyboard and mouse input over desktop machines.
Could it be a stand-alone windowing library in its own package?
It could be a lightweight SDL replacement for use cases in D where you don't really want to rely on SDL.

**Comment by dislogical** [comment]
I really like this idea. Unfortunately, I think this will take a lot of work, as there are a lot of other systems in Dash that are required by the adapters. You'll notice heavy usage of the `dash.utillity` package.

It's probably doable to break these out, but it's not especially high on our priorities list right now.

**Comment by p0nce** [comment]
I think it can be closed, as package de_window (https://github.com/devisualization/window) looks to fill this need for native windows in D.

**Comment by dislogical** [comment]
Alright, that works for us. We're actually about to remove our native adapters in favor of SDL anyway.
