### ISSUE TITLE
Windows on Laptops? does not render properly

### ISSUE THREAD

**Issue by ericchristenson** [Circular-Studios/Dash#25]
MacBook Pro (Early 2011), Windows 8: black screen
MacBook Air:, Windows 8.1: Texture doesn't display properly

**Comment by ScrappyOrc** [comment]
Alienware M17x, Windows 7, Raedon 6990M, Black screen

**Comment by ericchristenson** [comment]
Also fails on my desktop, ran GPUPerf and nothing is being output to the framebuffers from the geometry pass.

**Comment by wozniakty** [comment]
Still works on my home desktop.  Question: Are all of you running AMD cards?  I know the lab computers pop up the NVidia driver message and I also have nvidia here...I don't think that should be causing the issue, but that's my best bet at this point

**Comment by dislogical** [comment]
I just ran it on my Nvidia-powered desktop, and it ran fine. I think you may be on to something with that theory.

**Comment by brooklynlittell** [comment]
I have an AMD Radeon 6750M.

**Comment by ericchristenson** [comment]
totes an AMD issue...great
