### ISSUE TITLE
Implement OSX Adapter

### ISSUE THREAD

**Issue by dislogical** [Circular-Studios/Dash#3]
Implement a graphics and window adapter for use with OSX.

**Comment by ericchristenson** [comment]
Was this still something we wanted to try to include? Sounded like it wasn't worth the time right now at the last meeting.

**Comment by dislogical** [comment]
I think it's worth keeping around, in case we decide to implement it later, but not worth working on right now. Especially seeing as we don't even have rendering, this doesn't seem like a priority.

**Comment by dislogical** [comment]
Closing in favor of #207.
