### ISSUE TITLE
Add real names and profile pictures to Github

### ISSUE THREAD

**Issue by PxlBuzzard** [Circular-Studios/Dash#50]
Please comment here once you update your Github profiles.

**Comment by ericchristenson** [comment]
What? Is mine not showing it for you or something?

**Comment by PxlBuzzard** [comment]
If you are on the list you are missing one or both of the things, you personally are missing a first/last name.

**Comment by PxlBuzzard** [comment]
People still on the list, get it done.

**Comment by nicholasmcote** [comment]
Done, sorry about that.

**Comment by Daxelman** [comment]
Gravatar is literally hitler.

**Comment by PxlBuzzard** [comment]
Thank you everyone.
