### ISSUE TITLE
Enhance README

### ISSUE THREAD

**Issue by PxlBuzzard** [Circular-Studios/Dash#54]
Get that readme all fancied-up before GDC. This will also help as we begin interacting with the D community.

Potential Additions:
- Our Vision / Goals
- Important Wiki Links
- Links to our other repos (Speed, Sample Game)
- Engine Logo

Commits:
- 7b8923a3a16afb9dc04b089d60933f40a0a15dad: Added link to demo game.

**Comment by brooklynlittell** [comment]
- 20ac8384aef31a2819e46be61bd2448e83214a6f: Readme update
- b4e63785dce55d227ae7e1375d6856108854d10a: Readme update [Link fix]
