### ISSUE TITLE
Pick a license

### ISSUE THREAD

**Issue by PxlBuzzard** [Circular-Studios/Dash#6]
[Our previous license](https://github.com/ColdenCullen/Project-192/blob/master/LICENSE) is probably still good, but I would have the engine team all agree on something before copying it.

**Comment by dislogical** [comment]
I would be totally fine with using 192's license.

**Comment by PxlBuzzard** [comment]
Speaking of the 192 license, I updated it to properly reflect its original intent. https://github.com/ColdenCullen/Project-192/commit/b658a40a9f76aafd65a6c251d39a894bfe238ded
