### ISSUE TITLE
Add Circular Studios to LinkedIn

### ISSUE THREAD

**Issue by PxlBuzzard** [Circular-Studios/Dash#64]
Create a project on LinkedIn and add the group members to it.

**Comment by dislogical** [comment]
Where are we on this @theDerrickHunt?

**Comment by derrickhunt** [comment]
I had no idea I was assigned this. I can get this done asap.

**Comment by PxlBuzzard** [comment]
I've moved this issue into the Spectral Robot Task Force repo.
