### ISSUE TITLE
Move glsl out of shaders.d

### ISSUE THREAD

**Issue by ericchristenson** [Circular-Studios/Dash#68]
<p>Tyler and I were discussing the location of our shader code, and while the current system works fine for now the size, complexity and number of shaders will most likely increase as we continue to add features.
<p>We were thinking of a system where shaders can be paired in a file, i.ie. geometryVS and geometryFS and all the shader files could be included in their own package.
<p>Another concern is the ShaderUniform enum which will most likely become massive, but we were unable to think of a good solution right now.

**Comment by brooklynlittell** [comment]
I think we should try to figure out how to handle the ShaderUniform enum before progressing.

**Comment by ericchristenson** [comment]
Leaning towards not actually changing that at the moment, the only solution we came up with so far is some mixins that end up not saving us much

**Comment by brooklynlittell** [comment]
I think that's a good path to take.
