### ISSUE TITLE
Remove Required Meshes from Games Folder

### ISSUE THREAD

**Issue by wozniakty** [Circular-Studios/Dash#89]
Engine-necessary meshes like the unit-sphere or unit-square should be removed from the Meshes folder of the game, and instead embedded in the engine, most likely in a token string similar to the shaders.

**Comment by dislogical** [comment]
I think it may also make sense to move them out of the Assets manager and into their own variables to avoid name collisions with user meshes.

**Comment by ericchristenson** [comment]
Just leaving myself a reminder for when I get to this. 
Use:
[ReadFileFromMemory](http://assimp.sourceforge.net/lib_html/class_assimp_1_1_importer.html#a9b3c5e8b1042702f449e84a95b3324f6)
Example:
https://github.com/assimp/assimp/blob/master/test/unit/utImporter.cpp
