### ISSUE TITLE
Init time print bug

### ISSUE THREAD

**Issue by PxlBuzzard** [Circular-Studios/Dash#92]
![wat](https://f.cloud.github.com/assets/512416/2402737/1b655542-aa26-11e3-9199-4d2e904cbe86.PNG)

I assume this is because I use a custom font that is missing whatever character is trying to be drawn, but what the heck character needs to be there anyway?

**Comment by ericchristenson** [comment]
https://en.wikipedia.org/wiki/Mu_%28letter%29

**Comment by ericchristenson** [comment]
Yeah, this is just how windows seems to print "μ" in cmd, not really worth our time to do anything about it.
