### ISSUE TITLE
Modification of individual position members

### ISSUE THREAD

**Issue by brooklynlittell** [Circular-Studios/Dash#93]
Programmatically changing the individual x,y,z members of the transform object in GO appears to be broken. Current workaround: set position equal to a new vec3.

**Comment by wozniakty** [comment]
Hmm.  Eric had the same issue last milestone, and we pushed a fix for it.  On master I'm not having any problems modifying the x y and z.

**Comment by dislogical** [comment]
I'm 80% sure it's a shared issue.

**Comment by brooklynlittell** [comment]
We were trying this to make the compiler happy about shared:

`(cast()transform.position).x`

I think getting the fields that way worked fine, but setting them was definitely not working.

**Comment by wozniakty** [comment]
Yeah, I'm pretty sure that casting away shared gives you a local copy

**Comment by dislogical** [comment]
This is going to be a pretty for-serious issue. We can't exactly make transforms thread-local.
